---------------------------------------------------------------------
---------------------------------------------------------------------
-- DEPRECATED IN V2. 
-- Menu building is now entirely decoupled and event-driven.
-- F10 Menus are populated dynamically via common/menu/root.lua 
---------------------------------------------------------------------
