---------------------------------------------------------------------
-- TCS AIR FLIGHT MANAGER
-- State Machine Layer: Manages active air scenarios post-spawn.
-- Handles AWACS Calls, Threat Assessment, and Retreat/RTB logic.
---------------------------------------------------------------------
env.info("TCS(AIR.FLIGHT_MANAGER): loading")

TCS = TCS or {}
TCS.Air = TCS.Air or {}
TCS.Air.FlightManager = {}

--- Attaches the Flight Manager State Machine to a newly spawned environment.
-- @param envSpec The blueprint generated by the Architect.
-- @param spawnedGroups A table of the MOOSE GROUP objects spawned.
function TCS.Air.FlightManager.Attach(envSpec, spawnedGroups)
    if not envSpec or not spawnedGroups or #spawnedGroups == 0 then return end

    local tag = envSpec.missionType or "AIR_SCENARIO"
    local initialCount = envSpec.maxAirframes or TCS.Air.AliveAircraftCount(spawnedGroups)
    
    -- Initialize the State Machine Object
    local sm = {
        Tag = tag,
        Groups = spawnedGroups,
        InitialStrength = initialCount,
        Terminated = false,
        StartTime = timer.getTime(),
        EnvSpec = envSpec
    }

    -- 1. Initialize AWACS / GCI Calls
    -- Wait 3 seconds to simulate radar acquisition delay, then call BRAA
    SCHEDULER:New(nil, function()
        if sm.Terminated then return end
        
        -- Find the closest opposing player to use as the AWACS/BRAA reference
        local enemyCoalition = (sm.EnvSpec.coalition == coalition.side.RED) and coalition.side.BLUE or coalition.side.RED
        local activeClients = SET_CLIENT:New():FilterCoalition(enemyCoalition):FilterActive():FilterStart()
        
        local closestClient = nil
        local closestDist = math.huge
        local banditLead = sm.Groups[1] and sm.Groups[1]:GetUnit(1)
        
        if not banditLead then return end
        
        activeClients:ForEachClient(function(client)
            if client and client:IsAlive() then
                local dist = client:GetCoordinate():Get2DDistance(banditLead:GetCoordinate())
                if dist < closestDist then
                    closestDist = dist
                    closestClient = client
                end
            end
        end)

        local leadGroup = closestClient and closestClient:GetGroup() or nil
        local leadUnit = closestClient and closestClient:GetClientGroupUnit() or nil
        local closestBandit, _ = TCS.Air.ClosestBanditAndRange({Unit = leadUnit}, sm.Groups)
        
        if closestBandit and leadUnit then
            -- Initial BRAA Call
            TCS.Air.AwacsControllerCallBraa(leadGroup, leadUnit, closestBandit, "BANDITS", "", sm.Tag)
            
            -- Start Periodic Updates using the Group-based Controller (instead of Session)
            TCS.Air.StartAwacsUpdates(leadGroup, leadUnit, function()
                local r, _ = TCS.Air.ClosestBanditAndRange({Unit = leadUnit}, sm.Groups)
                if r and r:IsAlive() then return r end
                return nil
            end, "BANDITS", "track")
        end
    end, {}, TCS.Air.Settings.FLIGHT_MANAGER.RADAR_ACQUISITION_DELAY_SEC or 3)

    -- 2. Attrition & Retreat Monitor (The "Reactive" Loop)
    function sm:Monitor()
        if self.Terminated then return end
        
        -- Use the dynamic activeFlights pool from the spawner if available
        local currentGroups = self.EnvSpec.activeFlights or self.Groups
        local activeCount = TCS.Air.AliveAircraftCount(currentGroups)
        local totalLost = self.EnvSpec.totalLosses or 0
        
        if totalLost >= self.InitialStrength and activeCount == 0 then
            self:Terminate("DESTROYED")
            return
        end

        -- Zone Intrusion Monitoring (The Tactical Pre-Scramble trigger)
        if self.EnvSpec.missionType == "CAP" and self.EnvSpec.geometry and self.EnvSpec.geometry.anchor then
            local anchorVec3 = self.EnvSpec.geometry.anchor:GetVec3()
            local capRadius = (TCS.Air.Settings.FLIGHT_MANAGER.CAP_DETECTION_RADIUS_NM or 40) * 1852 
            local targetCoalition = (self.EnvSpec.coalition == coalition.side.RED) and coalition.side.BLUE or coalition.side.RED
            local intruderFound = false

            local vol = { id = world.VolumeType.SPHERE, params = { point = anchorVec3, radius = capRadius } }
            world.searchObjects(Object.Category.UNIT, vol, function(obj)
                if obj and obj:isExist() and obj:getCoalition() == targetCoalition then
                    local desc = obj:getDesc()
                    if desc and (desc.category == Unit.Category.AIRPLANE or desc.category == Unit.Category.HELICOPTER) then
                        intruderFound = true
                    end
                end
                return not intruderFound -- stop searching if we found one
            end)

            if intruderFound and not self.EnvSpec.IntruderActive then
                self.EnvSpec.IntruderActive = true
                if self.EnvSpec.ForceRelief then
                    self.EnvSpec.ForceRelief()
                    env.info(string.format("TCS(AIR.FLIGHT_MANAGER): Intruder detected in CAP zone %s. Triggering early relief scramble.", self.Tag))
                end
            elseif not intruderFound and self.EnvSpec.IntruderActive then
                self.EnvSpec.IntruderActive = false
                env.info(string.format("TCS(AIR.FLIGHT_MANAGER): CAP zone %s is clear of intruders.", self.Tag))
            end
        end

        -- Check Attrition Threshold (Retreat Logic)
        -- Read threshold from the Architect's successCriteria (e.g., 0.65 = 65% losses triggers retreat)
        local attritionThreshold = TCS.Air.Settings.FLIGHT_MANAGER.DEFAULT_ATTRITION_THRESHOLD or 0.65 
        if self.EnvSpec.successCriteria and self.EnvSpec.successCriteria[1] then
            attritionThreshold = self.EnvSpec.successCriteria[1].threshold or TCS.Air.Settings.FLIGHT_MANAGER.DEFAULT_ATTRITION_THRESHOLD or 0.65
        end

        local lossRatio = totalLost / self.InitialStrength
        if lossRatio >= attritionThreshold then
            local enemyCoalition = (self.EnvSpec.coalition == coalition.side.RED) and coalition.side.BLUE or coalition.side.RED
            local msg = string.format("AWACS: %s forces have taken heavy losses. They are breaking contact and regrouping!", self.Tag)
            MESSAGE:New(msg, 10):ToCoalition(enemyCoalition)
            if TCS.AWACS and TCS.AWACS.Say then TCS.AWACS.Say(msg) end
            
            self.EnvSpec.Terminated = true -- Choke off the Spawner
            self:OrderRetreat()
            self:Terminate("RETREAT")
            return
        end

        -- Schedule next check in 10 seconds
        SCHEDULER:New(nil, function() self:Monitor() end, {}, TCS.Air.Settings.FLIGHT_MANAGER.MONITOR_INTERVAL_SEC or 10)
    end

    function sm:OrderRetreat()
        local currentGroups = self.EnvSpec.activeFlights or self.Groups
        for _, g in ipairs(currentGroups) do
            if g and g:IsAlive() then
                -- Use MOOSE AUFTRAG to order a standard RTB, cancelling current intercepts
                local flightGroup = FLIGHTGROUP:New(g)
                flightGroup:AddMission(AUFTRAG:NewRTB())
            end
        end
    end

    function sm:Terminate(reason)
        self.Terminated = true
    end

    -- Start the monitoring loop
    sm:Monitor()
end
env.info("TCS(AIR.FLIGHT_MANAGER): ready")