
env.info("TCS(A2G.FORCES): loading")
TCS.A2G.Forces={
  MECH_INF={MIXED=3,AIRDEF=0.5,ARMOR=0.3,TRANSPORT=0.5,JTAC=0.5},
  MECH_INF_REAR={MIXED=3,AIRDEF=1.0,ARMOR=0.3,TRANSPORT=1.0},
  SEAD={AIRDEF=2.0, MIXED=1.0},
  DEAD={AIRDEF=1.0, ARMOR=1.0, MIXED=1.0},
  STRIKE={ARMOR=2.0, TRANSPORT=1.0, AIRDEF=0.5},
  MAR_CONVOY={SHIP_CARGO=3, SHIP_ESCORT=1},
  MAR_HARBOR={SHIP_DOCKED=2, AIRDEF=1, STRUCTURE=4},
  SUW_SAG={SHIP_ESCORT=4}
}
